version: "3.8"

services:

  neo4j:
    image: neo4j:4.4.8
    container_name: mac0350-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: none
